# Generated by Django 5.0.4 on 2024-07-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://canape.cdnflexcatering.com/themes/frontend/default/images/img-placeholder.png', max_length=500),
        ),
    ]
